### ISSUE TITLE
Scrollbar rendred badly for GTK3

### ISSUE THREAD

**Issue by Iey4iej3** [killhellokitty/DeLorean-Dark-3.18#5]
Here's the snapshot for FireFox:

![2017-06-02-104402_114x651_scrot](https://cloud.githubusercontent.com/assets/1880768/26718209/87174750-4780-11e7-8b2c-505e44671d3a.png)

**Comment by killhellokitty** [comment]
This theme is VERY old Gtk3.18.  I intend on updating it in the near future (time willing).
